package team.neoradiance.immersiveadventuring;

import java.util.concurrent.CompletableFuture;

import net.minecraft.core.HolderLookup;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.PackOutput;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.data.event.GatherDataEvent;
import team.neoradiance.immersiveadventuring.common.nylon.NylonBlockTagsProvider;
import team.neoradiance.immersiveadventuring.common.nylon.NylonRecipeProvider;
import team.neoradiance.immersiveadventuring.common.nylon.NylonItemTagsProvider;

/**
 * Data Generator Handler
 * <p>
 * This class is responsible for registering all data providers for the mod, including:
 * <ul>
 *   <li>Recipe providers (vanilla and Immersive Engineering)</li>
 *   <li>Tag providers (item and block tags)</li>
 * </ul>
 * <p>
 * <h2>Data Generation Workflow</h2>
 * <p>
 * <h3>Initialization</h3>
 * <ol>
 *   <li><strong>Event Subscription</strong>: The class is annotated with {@code @EventBusSubscriber} to listen for
 *       the {@code GatherDataEvent}.</li>
 *   <li><strong>Event Handling</strong>: When the {@code gatherData} method is called, it initializes the data generators.</li>
 *   <li><strong>Provider Registration</strong>: All data providers are registered with the data generator.</li>
 * </ol>
 * <p>
 * <h3>Immersive Engineering Recipe Generation Details</h3>
 * <p>
 * <h4>IE Recipe Generation Process</h4>
 * <ol>
 *   <li><strong>Root Initialization</strong>: In IE's {@code IEDataGenerator.gatherData()} method:
 *       <pre>gen.addProvider(true, new RootRecipeProvider(output, lookup));</pre></li>
 *   <li><strong>Recipe Builder Creation</strong>: In IE's {@code OreRecipes.buildRecipes()} method:
 *       <pre>MetalPressRecipeBuilder pressBuilder = MetalPressRecipeBuilder.builder()
 *           .input(metal.getIngot())
 *           .mold(Molds.MOLD_PLATE)
 *           .output(plate, 1)
 *           .setEnergy(2400);</pre></li>
 *   <li><strong>Recipe Building</strong>: The recipe is built and saved:
 *       <pre>pressBuilder.build(out, toRL("metalpress/plate_"+metal.getName()));</pre></li>
 *   <li><strong>Recipe Creation</strong>: In IE's {@code MetalPressRecipeBuilder.build()} method:
 *       <pre>MetalPressRecipe recipe = new MetalPressRecipe(output, input, mold.asItem(), energy);
 *       out.accept(name, recipe, null, getConditions());</pre></li>
 * </ol>
 * <p>
 * <h4>Key Components</h4>
 * <ul>
 *   <li><strong>Output</strong>: {@code TagOutput} object specifying the recipe result</li>
 *   <li><strong>Input</strong>: {@code IngredientWithSize} object specifying the required input</li>
 *   <li><strong>Mold</strong>: {@code ItemLike} object specifying the required mold</li>
 *   <li><strong>Energy</strong>: {@code int} value specifying the energy required (typically 2400 for plate pressing)</li>
 *   <li><strong>RecipeOutput</strong>: Object used to accept and save the generated recipe</li>
 *   <li><strong>Recipe Location</strong>: Resource location specifying where to save the recipe</li>
 * </ul>
 * <p>
 * <h3>Tag Generation</h3>
 * <p>
 * Tags are generated for better compatibility and extensibility:
 * <ul>
 *   <li><strong>Item Tags</strong>: Generated by {@code NylonItemTagsProvider} for items like nylon ingots and plates</li>
 *   <li><strong>Block Tags</strong>: Generated by {@code NylonBlockTagsProvider} for blocks like nylon blocks</li>
 *   <li><strong>Tag Namespace</strong>: Uses the {@code c} namespace for common compatibility</li>
 *   <li><strong>Tag Structure</strong>: Organized by category (e.g., {@code c:ingots/nylon}, {@code c:plates/nylon})</li>
 * </ul>
 */
@EventBusSubscriber(modid = Lib.MOD_ID)
public class ModDataGeneratorHandler {
    @SubscribeEvent
    public static void gatherData(GatherDataEvent event) {
        // Data generators may require some of these as constructor parameters.
        // See below for more details on each of these.
        DataGenerator generator = event.getGenerator();
        PackOutput output = generator.getPackOutput();
        ExistingFileHelper existingFileHelper = event.getExistingFileHelper();
        CompletableFuture<HolderLookup.Provider> lookupProvider = event.getLookupProvider();

        // Register the provider.
        generator.addProvider(
                // A boolean that determines whether the data should actually be generated.
                // The event provides methods that determine this:
                // event.includeClient(), event.includeServer(),
                // event.includeDev() and event.includeReports().
                // Since recipes are server data, we only run them in a server datagen.
                event.includeServer(),
                // Our provider.
                new NylonRecipeProvider(output, lookupProvider)
        );
        // Other data providers here.
        NylonBlockTagsProvider nylonBlockTagsProvider = new NylonBlockTagsProvider(output, lookupProvider, existingFileHelper);
        generator.addProvider(
                event.includeServer(),
                nylonBlockTagsProvider
        );
        generator.addProvider(
                event.includeServer(),
                new NylonItemTagsProvider(output, lookupProvider, nylonBlockTagsProvider.contentsGetter(), existingFileHelper)
        );
    }
}